export {
  PROTOCOL_VERSION,
  EnvelopeSchema,
  createEnvelope,
  type Envelope,
} from './envelope.js'

export { ProtocolError, parseEnvelope } from './parse.js'

export {
  // enums / primitives
  PermissionDecisionSchema,
  RiskLevelSchema,
  SessionPhaseSchema,
  SlashCommandSchema,
  ErrorCodeSchema,
  MessageRoleSchema,
  type PermissionDecision,
  type RiskLevel,
  type SessionPhase,
  type SlashCommand,
  type ErrorCode,
  type MessageRole,
  // client → server
  AuthPairPayloadSchema,
  AuthHelloPayloadSchema,
  SessionListPayloadSchema,
  SessionCreatePayloadSchema,
  SessionOpenPayloadSchema,
  SessionDeletePayloadSchema,
  ChatSendPayloadSchema,
  ChatAbortPayloadSchema,
  SlashRunPayloadSchema,
  PermissionRespondPayloadSchema,
  FsListPayloadSchema,
  FsReadPayloadSchema,
  ConfigGetPayloadSchema,
  ConfigSetPayloadSchema,
  type AuthPairPayload,
  type AuthHelloPayload,
  type SessionListPayload,
  type SessionCreatePayload,
  type SessionOpenPayload,
  type SessionDeletePayload,
  type ChatSendPayload,
  type ChatAbortPayload,
  type SlashRunPayload,
  type PermissionRespondPayload,
  type FsListPayload,
  type FsReadPayload,
  type ConfigGetPayload,
  type ConfigSetPayload,
  // server → client
  AuthOkPayloadSchema,
  AuthPairResultPayloadSchema,
  SessionSummarySchema,
  SessionListResultPayloadSchema,
  ChatMessageSchema,
  PermissionRequestPayloadSchema,
  StatusPayloadSchema,
  SessionSnapshotPayloadSchema,
  MessageDeltaPayloadSchema,
  MessageCompletedPayloadSchema,
  ToolStartedPayloadSchema,
  ToolProgressPayloadSchema,
  ToolCompletedPayloadSchema,
  DiffAvailablePayloadSchema,
  ErrorPayloadSchema,
  type AuthOkPayload,
  type AuthPairResultPayload,
  type SessionSummary,
  type SessionListResultPayload,
  type ChatMessage,
  type PermissionRequestPayload,
  type StatusPayload,
  type SessionSnapshotPayload,
  type MessageDeltaPayload,
  type MessageCompletedPayload,
  type ToolStartedPayload,
  type ToolProgressPayload,
  type ToolCompletedPayload,
  type DiffAvailablePayload,
  type ErrorPayload,
  // catalogs
  ClientMessageTypes,
  ServerMessageTypes,
  type ClientMessageType,
  type ServerMessageType,
} from './messages.js'
